drbdtest: do not modify dmesg streams while iterating
This fixes the following error:

Exception in thread Thread-2 (dmesg_pipe):
Traceback (most recent call last):
  File \"/usr/lib/python3.10/threading.py\", line 1016, in _bootstrap_inner
    self.run()
  File \"/usr/lib/python3.10/threading.py\", line 953, in run
    self._target(*self._args, **self._kwargs)
  File \"/virter/workspace/tests/python/drbdtest.py\", line 1459, in dmesg_pipe
    self.ssh.pipeIO(self.dmesg_process, stdout=self.dmesg_pid_trap)
  File \"/usr/local/lib/python3.10/dist-packages/lbpytest/controlmaster.py\", line 190, in pipeIO
    check_io()
  File \"/usr/local/lib/python3.10/dist-packages/lbpytest/controlmaster.py\", line 182, in check_io
    out.write(line_bytes.decode('utf-8') + '\\n')
  File \"/virter/workspace/tests/python/drbdtest.py\", line 211, in write
    self.target.write(message)
  File \"/virter/workspace/tests/python/drbdtest.py\", line 187, in write
    for stream in self.streams:
RuntimeError: Set changed size during iteration

The above error sometimes occurred when running the test "verify". The
test then failed with the following error because the dmesg output was
no longer being captured:

Wanted '{405504, 5488640, 5492736, 16302080}', but got 'set()'.
...
RuntimeError: assert trigger